spring.application.name=loan-system

# Salva o banco em um arquivo chamado "loandb" na pasta do projeto
spring.datasource.url=jdbc:h2:file:./loandb;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update